name: Sam Deploy app
run-name: ${{ github.actor }} is deploying to main
on:
  push:
    branches:
      - main
jobs:
    deploy:
      name: deploy app
      runs-on: ubuntu-latest
      steps:
        - run: echo "Event picked up on a ${{ github.event_name }} event."
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v3
        - uses: aws-actions/setup-sam@v2
        - uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - run: echo "AWS access credentials pulled from env."
        - run: sam build --use-container
        - run: | 
              sam deploy \
                --no-confirm-changeset \
                --no-fail-on-empty-changeset \
                --config-env qa \
                --stack-name "gha-app-qa"
                --capabilities CAPABILITY_IAM \

        - run: echo "This job's status is ${{ job.status }}."

    # teams-notify:
    #   name: Notify on teams
    #   needs: deploy
    #   runs-on: ubuntu-latest
    #   steps:
    #     - uses: actions/checkout@master
    #     - name: Microsoft Teams Notification
    #       uses: skitionek/notify-microsoft-teams@master
    #       with:
    #         webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
    #         dry_run: False
    #         message: |
    #           🚀 *Deployment Notification*
    #           - Repository: `${{ github.repository }}`
    #           - Branch: `${{ github.ref_name }}`
    #           - Actor: `${{ github.actor }}`
    #           - Status: `${{ needs.deploy.result }}`
    #           - [View Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})