name: Secret reader
run-name: ${{ github.actor }} is running workflow dispatch
on:
  workflow_dispatch
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: read access key id
      run: echo "Aws access key is  ${{ secrets.AWS_ACCESS_KEY_ID }}"
    - name: read access key secret
      run: echo "AWS access key secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}"

  teams-notify:
    name: Notify on teams
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          dry_run: False
          message: |
            🚀 *Deployment Notification*
            - Repository: `${{ github.repository }}`
            - Branch: `${{ github.ref_name }}`
            - Actor: `${{ github.actor }}`
            - Status: `${{ needs.deploy.result }}`
            - [View Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

