name: Secret reader
run-name: ${{ github.actor }} is running workflow dispatch
on:
  workflow_dispatch
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: read access key id
      run: echo "Aws access key is  ${{ secrets.AWS_ACCESS_KEY_ID }}"
    - name: read access key secret
      run: echo "AWS access key secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}"

  teams-notify:
    name: Notify on teams
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          dry_run: False
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          raw: >-
            {
              "type": "message",
              "attachments": [
                {
                  "contentType": "application/vnd.microsoft.card.adaptive",
                  "content": {
                    "type": "AdaptiveCard",
                    "body": [
                      {
                        "type": "ColumnSet",
                        "columns": [
                          {
                            "type": "Column",
                            "width": "auto",
                            "items": [
                              {
                                "type": "Image",
                                "width": "56px",
                                "height": "56px",
                                "altText": "Logo",
                                "style": "RoundedCorners",
                                "url": "https://static-00.iconduck.com/assets.00/githubactions-icon-2048x2048-ipqow27x.png"
                              }
                            ]
                          },
                          {
                            "type": "Column",
                            "width": "stretch",
                            "items": [
                              {
                                "type": "TextBlock",
                                "text": "Bug 2837 - Icons not rendering in dark mode",
                                "wrap": true,
                                "weight": "Bolder"
                              },
                              {
                                "type": "ColumnSet",
                                "targetWidth": "AtLeast:Standard",
                                "columns": [
                                  {
                                    "type": "Column",
                                    "width": "auto",
                                    "items": [
                                      {
                                        "type": "Icon",
                                        "name": "CircleSmall",
                                        "color": "Attention",
                                        "style": "Filled",
                                        "size": "Small"
                                      }
                                    ],
                                    "horizontalAlignment": "Center",
                                    "verticalContentAlignment": "Center"
                                  },
                                  {
                                    "type": "Column",
                                    "width": "auto",
                                    "items": [
                                      {
                                        "type": "TextBlock",
                                        "text": "Job Status",
                                        "wrap": true
                                      }
                                    ],
                                    "spacing": "None",
                                    "verticalContentAlignment": "Center"
                                  },
                                  {
                                    "type": "Column",
                                    "width": "auto",
                                    "items": [
                                      {
                                        "type": "TextBlock",
                                        "text": ":",
                                        "wrap": true
                                      }
                                    ],
                                    "spacing": "Small",
                                    "verticalContentAlignment": "Center"
                                  },
                                  {
                                    "type": "Column",
                                    "width": "auto",
                                    "items": [
                                      {
                                        "type": "TextBlock",
                                        "text": "${{ job.status }}",
                                        "wrap": true
                                      }
                                    ],
                                    "spacing": "Small",
                                    "verticalContentAlignment": "Center"
                                  }
                                ]
                              }
                            ]
                          }
                        ]
                      },
                      {
                        "type": "ActionSet",
                        "actions": [
                          {
                            "type": "Action.OpenUrl",
                            "title": "Job URL",
                            "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                          }
                        ]
                      }
                    ],
                    "version": "1.5"
                  }
                }
              ]
            }


          
      - name: Push to teams complete
        run: echo "Pushing to teams..."

