name: Secret reader
run-name: ${{ github.actor }} is running workflow dispatch
on:
  workflow_dispatch
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: read access key id
      run: echo "Aws access key is  ${{ secrets.AWS_ACCESS_KEY_ID }}"
    - name: read access key secret
      run: echo "AWS access key secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}"

  teams-notify:
    name: Notify on teams
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Send Teams message via Power Automate
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"status": "${{ job.status }}", "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
            https://prod-61.westus.logic.azure.com:443/workflows/eb979f73f84c48b4887d64e1bedd4e7c/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=0MwCk9GVd3iP-roWT_wWUQqUo6KFJFTtSFsSRwcsM_0
          
      - name: Push to teams complete
        run: echo "Pushing to teams..."

