name: Secret reader
run-name: ${{ github.actor }} is running workflow dispatch
on:
  workflow_dispatch
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: read access key id
      run: echo "Aws access key is  ${{ secrets.AWS_ACCESS_KEY_ID }}"
    - name: read access key secret
      run: echo "AWS access key secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}"

